[workspace]

[package]
name = "text_embedding_qdrant"
version = "0.1.0"
edition = "2024"

[dependencies]
synor = { path = "../../../rust/sdk/synor", features = [
    "qdrant",
    "text",
    "fastembed",
] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15"
