[workspace]

[package]
name = "text_embedding_lancedb"
version = "0.1.0"
edition = "2024"

[dependencies]
synor = { path = "../../../rust/sdk/synor", features = [
    "lancedb",
    "text",
    "fastembed",
] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
dotenvy = "0.15"
