[workspace]

[package]
name = "files_to_sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
synor = { path = "../../../rust/sdk/synor", features = ["sqlite"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
] }
