name: Link Check

on:
  pull_request:
    branches: [main]
    paths:
      - "docs/**/*.md"
      - "docs/**/*.mdx"
      - ".lycheeignore"
      - ".github/workflows/links.yml"
  push:
    branches: [main]
    paths:
      - "docs/**/*.md"
      - "docs/**/*.mdx"
      - ".lycheeignore"
      - ".github/workflows/links.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  link-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Restore lychee cache
        if: github.event_name != 'schedule'
        uses: actions/cache@v6
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run link checker
        id: lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2
        with:
          args: --accept 200,203,301..=304,403,429 --cache --max-cache-age 1d --verbose --no-progress --root-dir './docs' 'docs/**/*.md' 'docs/**/*.mdx'
          fail: false
          format: markdown
          jobSummary: true
          output: ./lychee/out.md

      - name: Create issue from report
        if: steps.lychee.outputs.exit_code == '2' && github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue

      - name: Fail on broken links
        if: steps.lychee.outputs.exit_code != '0'
        run: exit 1
